Allow toolchain to be passed in as an input

diff --git a/.github/actions/ci-rust-setup/action.yml b/.github/actions/ci-rust-setup/action.yml
--- a/.github/actions/ci-rust-setup/action.yml
+++ b/.github/actions/ci-rust-setup/action.yml
@@ -11,16 +11,26 @@ inputs:
   components:
     description: 'A comma separated list of extra components you want to install'
     required: false
+  toolchain:
+    description: 'The toolchain to use. If not specified, the rust-toolchain file will be used'
+    required: false
 
 runs:
   using: composite
   steps:
-    - name: Read rust-toolchain file from repository
+    - name: Get toolchain from input OR rust-toolchain file
       id: gettoolchain
       shell: bash
       run: |-
-        [ ! -f rust-toolchain ] && echo "***ERROR*** NEED rust-toolchain FILE IN ROOT OF REPOSITORY" >&2; exit 1
-        echo "toolchain=$(cat rust-toolchain)" >> $GITHUB_OUTPUT
+        RUST_TOOLCHAIN="${{ inputs.toolchain }}"
+        if [ ! -f rust-toolchain ] && [ -z "${RUST_TOOLCHAIN}" ]; then
+          echo "***ERROR*** NEED rust-toolchain FILE IN ROOT OF REPOSITORY" >&2
+          exit 1
+        fi
+        if [ -z "${RUST_TOOLCHAIN}" ]; then
+          RUST_TOOLCHAIN="$(cat rust-toolchain)"
+        fi
+        echo "toolchain=\"${RUST_TOOLCHAIN}\"" >> $GITHUB_OUTPUT
     - name: Install ${{ steps.gettoolchain.outputs.toolchain }} Rust toolchain
       id: toolchain
       # Commit date is Sep 19, 2023
